[package]
name = "basic-jit-bench"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "mandelbrot-jit-bench"
path = "src/mandelbrot.rs"

[[bin]]
name = "clocksp5-jit-bench"
path = "src/clocksp5.rs"

[dependencies]
ricochet = { path = "../.." }
cranelift-codegen = "=0.135.2"
cranelift-frontend = "=0.135.2"
cranelift-jit = "=0.135.2"
cranelift-module = "=0.135.2"
cranelift-native = "=0.135.2"
cranelift-object = "=0.135.2"
