[package]
name = "mandelbrot-jit-bench"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
acorn-2026 = { path = "../.." }
cranelift-codegen = "=0.135.2"
cranelift-frontend = "=0.135.2"
cranelift-jit = "=0.135.2"
cranelift-module = "=0.135.2"
cranelift-native = "=0.135.2"
cranelift-object = "=0.135.2"
